import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import ReduxProvider from "@/store/provider";
import { getCookie } from "cookies-next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FundFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ApolloWrapper>
            <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
              <Navbar />
              {children}
            </div>
          </ApolloWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
